### PR TITLE
Fix infinite loop while parsing coap options, add unit test for that.

### PR DESCRIPTION
**Pull request by simosillankorva**

### CODE REVIEW

**Comment by simosillankorva** [comment]
Janne that would be an other task to make different kind of test cases?

**Comment by JanneKiiskila** [comment]
Simo, the commit message itself hasn't changed yet. Please also comment to @kjbracey-arm 's comments.

**Comment by simosillankorva** [comment]
@kjbracey-arm It looks like it is now parsing the uri correctly.  

The reason why I did not change the initial value of i is that it would have changed the calculation (I assumed that the calculation would be done correcty). Tried to use the initial value 0 and got several errors when running the unit tests.

The comparation of the packet_left_len does look wrong. I can fix that and include it to this pull request.

**Comment by kjbracey-arm** [comment]
I was thinking `i` was just a length check, but it's more complex than that, isn't it... So `i` is actually the index into `packet_data_ptr`, and we start by assuming `packet_data_ptr[0]` is last byte of the first option/len descriptor?

So packet_left_len must include that extra byte?

Initial thought is that it doesn't even need to be a while loop - for (;;) would do as it breaks as soon as i is incremented enough.

But it's worse than that. `packet_left_len` isn't even correct, it can overrun because `message_left` isn't updated to reflect the option header consumed before calling `sn_coap_parser_options_parse_multiple_options`.

I think we've opened a can of worms here.

https://twitter.com/jonathan_blow/status/267836389956149248

**Pull request merged**
